# Site settings
title: 丑矬穷
email: lbp0408@gmail.com
description: "又一个github-jekyll博客"
baseurl: ""
url: "http://lbp0200.github.io"
twitter_username: 
github_username:  lbp0200

# Build settings
markdown: redcarpet
permalink: pretty
