categories: 分类
search: 搜索
tags: 标签
tagcloud: 标签云
prev: 前一篇
next: 下一篇
comment: 评论
archive: 博文
page: 页面 %d
recent_posts: 最近发表
archive_a: 归档
archive_b: 归档：%s
page: 第 %d 页

post:
  updated: 最近更新
  Tagged: 标签

menu:
  Home: 主页
  About: 关于
  Archives: 归档